baseURL = "https://bioarchlinux.org/"
languageCode = "en-us"
title = "BioArchLinux"
theme = "hugo-theme-bioarchlinux"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
  Name = "Docker"
  URL = "https://hub.docker.com/r/bioarchlinux/bioarchlinux"
  Title = "Get BioArchLinux on docker"
  weight = 1

[[menu.main]]
  Name = "WSL"
  URL = "https://github.com/BioArchLinux/wsl"
  Title = "Get BioArchLinux on WSL"
  weight = 0

[[menu.main]]
  Name = "Status"
  URL = "https://build.bioarchlinux.org/"
  Title = "Find and track bugs"
  weight = -1

[[menu.main]]
  Name = "Repository"
  URL = "https://repo.bioarchlinux.org"
  Title = "BioArchLinux Database"
  weight = -2

[[menu.main]]
  Name = "Wiki"
  URL = "https://wiki.bioarchlinux.org/"
  Title = "Community documentation"
  weight = -3

[[menu.main]]
  Name = "Chat"
  URL = "https://matrix.to/#/#bioarchlinux:matrix.org"
  Title = "Community chat"
  weight = -4

[[menu.main]]
  Name = "Packages"
  URL = "https://github.com/BioArchLinux/Packages"
  Title = "BioArchLinux Git Repository"
  weight = -5

[[menu.main]]
  Name = "Home"
  URL = "https://bioarchlinux.org/"
  Title = "Return to the main page"
  weight = -6

[[menu.sidebar]]
  Name = "Usage"
  URL = "https://wiki.bioarchlinux.org/index.php?title=Usage"
  Title = "Usage"
  weight = -1

[[menu.sidebar]]
  Name = "Mirror"
  URL = "https://raw.githubusercontent.com/BioArchLinux/mirror/main/pacman.conf.bio"
  Title = "Mirror"
  weight = 0

[[menu.sidebar]]
  Name = "Contribution"
  URL = "https://wiki.bioarchlinux.org/index.php?title=Contribution"
  Title = "Contribution"
  weight = 1

[[menu.sponsor]]
  Name = "xTom"
  URL = "https://v.ps/"
  Title = "xTom"
  weight = 1
